### ISSUE TITLE
The ghost weaver repair beam is glitchy when using industrial revolution 2 mod

### ISSUE THREAD

**Issue by stefanaonx** [stefanaonx/spidertron-extended#19]
The ghost weaver repair beam is glitchy when using industrial revolution 2 mod
https://cdn.discordapp.com/attachments/928016835910176808/953614902323466260/unknown.png

Need new animation for the 

data.raw['beam']['weaver-repair-beam'].head.filename = "__spidertron-extended__/graphics/spidertron_builder_laser_body_HD_1.png"

data.raw['beam']['weaver-repair-beam'].tail.filename = "__spidertron-extended__/graphics/spidertron_builder_laser_end_HD_1.png"
data.raw['beam']['weaver-repair-beam'].tail.width = 55
data.raw['beam']['weaver-repair-beam'].tail.height = 31
data.raw['beam']['weaver-repair-beam'].tail.frame_count = 16

data.raw['beam']['weaver-repair-beam'].body.filename = "__spidertron-extended__/graphics/spidertron_builder_laser_body_HD_1.png"
data.raw['beam']['weaver-repair-beam'].body.width = 16
data.raw['beam']['weaver-repair-beam'].body.height = 12
data.raw['beam']['weaver-repair-beam'].body.frame_count = 32

need new animations for builder laser body and builder laser end that has the frame count that is written in the code, ping me if you need more info :)

**Comment by Stargateur** [comment]
> 14.157 Error ModManager.cpp:1558: Error while loading entity prototype "weaver-repair-beam" (beam): Beam animation frame count mismatch. Head (8) must have same number of frames as tail (16).
Modifications: Spidertron Extended

**Comment by stefanaonx** [comment]
@Stargateur Can i have a list of all the mods you are using currently? because i have 2.3.2 Industrial Revolution with 0.3.14 spidertron extended and the game still works. So most likely there is another mod interfering.

**Comment by Stargateur** [comment]
I don't think it's was a mod conflict problem looking at the error message

```none
{
  ["Armored-train"] = "0.4.6",
  ArmouredBiters = "1.1.6",
  ArtilleryShellStack = "0.0.2",
  AutoDeconstruct = "0.3.3",
  AutoTrash = "5.3.13",
  Automatic_Train_Painter = "1.1.4",
  BottleneckLite = "1.2.4",
  DeadlockBlackRubberBelts = "1.0.2",
  DeadlockLargerLamp = "1.5.0",
  DeadlockResearchNotifications = "1.0.2",
  EnableResearchQueue = "1.0.4",
  FactorySearch = "1.9.3",
  FluidWagonColorMask = "1.1.0",
  GhostScanner = "1.6.5",
  HallOfFame = "1.14.0",
  IndustrialRevolution = "2.3.2",
  IndustrialRevolutionStacking = "1.0.1",
  IslandStart = "1.1.0",
  LSlib = "2020.12.12",
  Milestones = "1.3.8",
  ["Moar-Radar"] = "0.6.1",
  ModuleInserter = "5.2.4",
  MushroomCloud = "1.0.17",
  NoInfinite = "0.0.0",
  NuclearFuelStack = "0.0.0",
  OmegaDrill = "0.2.3",
  OreEraser = "1.5.6",
  ["Orphan Finder"] = "1.1.3",
  RateCalculator = "2.4.4",
  RecipeBook = "3.4.5",
  Repair_Turret = "1.0.2",
  RitnLib = "0.6.0",
  RotatableBatteries = "1.0.3",
  SchallCircuitGroup = "1.1.0",
  SchallCombatRobotics = "1.1.0",
  SchallEntityInspector = "1.1.2",
  SchallMapTag = "1.1.1",
  SchallModulePlacement = "1.1.2",
  SchallModules = "1.1.0",
  SchallOverseasRailway = "1.2.0",
  SchallRadarAlignment = "1.1.2",
  SchallRailwayController = "1.1.4",
  SchallRemainsPickup = "1.1.1",
  SchallSatelliteController = "1.1.2",
  SchallSuit = "1.1.1",
  SchallTransportGroup = "1.1.0",
  SchallUncraft = "1.1.0",
  SchallVirtualSignal = "1.1.2",
  Searchlight = "1.1.2",
  ["Shortcuts-ick"] = "1.1.27",
  SmallNightvisionRevived = "1.1.4",
  SmoothWarnings = "1.0.4",
  SpidertronEnhancements = "1.8.8",
  ["Squeak Through"] = "1.8.2",
  ["Story-Missions"] = "2.2.9",
  Teleporters = "1.0.5",
  ["Todo-List"] = "19.2.0",
  VehicleSnap = "1.18.4",
  VilsClearNightvision = "1.0.1",
  WhereIsMyBody = "1.1.3",
  WideChests = "4.0.2",
  WireShortcuts = "1.1.9",
  YARM = "0.8.207",
  ["aai-containers"] = "0.2.11",
  ["aai-signal-transmission"] = "0.4.7",
  ["aai-signals"] = "0.6.1",
  ["aai-vehicles-ironclad"] = "0.6.5",
  ["alien-biomes"] = "0.6.7",
  ["alien-biomes-hr-terrain"] = "0.6.1",
  ["automatic-station-painter"] = "1.0.5",
  base = "1.1.69",
  blueprint_flip_and_turn = "101.8.6",
  ["bullet-trails"] = "0.6.2",
  ["combat-mechanics-overhaul"] = "0.6.22",
  ["deadlock-beltboxes-loaders"] = "2.4.2",
  ["equipment-gantry"] = "0.1.5",
  ["even-distribution"] = "1.0.10",
  ["extended-descriptions"] = "1.0.17",
  flib = "0.11.1",
  ["grappling-gun"] = "0.3.2",
  hardened_pipes = "1.1.0",
  howfardiditgo = "1.1.0",
  informatron = "0.2.3",
  ["inventory-repair"] = "19.1.0",
  jetpack = "0.3.5",
  ["manual-inventory-sort"] = "2.2.5",
  ["osm-lib"] = "1.1.30",
  ["power-grid-comb"] = "1.1.0",
  pump = "1.1.3",
  ["resourcehighlighter-dark"] = "2.0.6",
  ["rso-mod"] = "6.2.20",
  safefill = "1.0.10",
  ["shield-projector"] = "0.1.6",
  simhelper = "1.1.4",
  ["spawner-alert"] = "0.1.8",
  ["spidertron-extended"] = "0.3.14",
  stdlib = "1.4.7",
  textplates = "0.6.9",
  ["train-log"] = "1.1.5",
  ["train-station-overview"] = "3.0.0",
  tree_collision = "1.1.0",
  ["wret-beacon-rebalance-mod"] = "1.0.14",
  yemtositemcount = "0.1.6"
}
```

Not sure it's help ;)

maybe `SpidertronEnhancements` or `IndustrialRevolutionStacking` or `deadlock-beltboxes-loaders`.

I more think there is a problem in your mod:

https://github.com/stefanaonx/spidertron-extended/blob/e9378f4e04a6872151a2b9a5c473c7cc64dbe1e3/compatibility/IndustrialRevolution.lua#L8-L16

look weird you override something you just override.

**Comment by Stargateur** [comment]
Sorry I forget it may be important factorio 1.1.69

**Comment by stefanaonx** [comment]
The mod list crashes immediately from other mods not just spidertron-extended: https://cdn.discordapp.com/attachments/928016835910176808/1021059723577016470/unknown.png

**Comment by Stargateur** [comment]
Very weird I should also have this. That come from the breaking change in 1.1.69 I will make a PR

https://github.com/Klonan/Repair_Turret/blob/c72b7fc83092489401ab95434edf97db33151187/data/entities/repair_turret/repair_turret.lua#L90-L98

Anyway, I found the conflict mod needed:

```rust
   1.169 Loading mod DeadlockBlackRubberBelts 1.0.2 (data.lua)
   1.179 Loading mod spidertron-extended 0.3.14 (data.lua)
   1.199 Loading mod IndustrialRevolution 2.3.2 (data.lua)
```

Better ^^, thus I looked a little the code I got no idea what the fuck is happening.

**Comment by stefanaonx** [comment]
Also noticed that the compatibility is no longer required, was checking now if it has any problems with other mods right now, but yes overall just removing compatibility seems to fix the issue. Gonna finish testing and make a pull request and add new version.

**Comment by stefanaonx** [comment]
Removing compatibility with Industrial Revolution.
